### PR TITLE
Frontend testing and polishing up website

### PR DESCRIPTION
**Pull request by Sophieeeeeeeee**
## Context

After major progress on the development of the website is being made, the focus is shifted to polishing up the codes, testing the codes and fixing any bugs encountered in the process. Fixes issues: https://github.com/autotrader-plus/traderautoplus-app/issues/4 and https://github.com/autotrader-plus/traderautoplus-app/issues/6

## Your Changes

Fixed delayed state variable change in post request to back end
Fixed Sign in page alarm pop up
Fixed Sign up page drop down box displaying selected option
Fixed car details aka loan page accessing not from browse page 
Documentation added

Front end testing is done by @jiah29 and @elizabethhli. 

**Type of change** (select all that apply):

- [ ] New feature (additional functionality separate from existing code)
- [ ] Refactoring (changing code structure only)
- [x] Breaking change (changing code functionality)
- [x] Documentation update (adding more comments)
- [x] Bug fix (non-breaking change that solves an error/issue)
- [ ] User Interface change (design changes)
- [x] Test update (adding test code)
- [ ] Other (please specify):

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [x] Code has been properly tested
- [x] Code has been properly documented
- [x] One or two people have reviewed this pull request

### CODE REVIEW

**Review by jiah29 — APPROVED** [review]
Everything looks good!

**Review by elizabethhli — COMMENTED** [review]
In Button.js, line 16 is "Invalid type syntax"
In Welcome.css, can we remove the commented out line on line 11
In Welcome.js, do we need the console.log("hey") whenever the Sign In button was clicked?
Aside from these 3 things it looks good!! YAY

**Review by parthaba — APPROVED** [review]
Everything is commented, clean and code is tested/works

**Review by Danx1129 — APPROVED** [review]
Looks good??

**Pull request merged**
